spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: eureka-server.cfapps.eu20.hana.ondemand.com
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # defaultZone: http://${EUREKA_SERVER_NAME:localhost}:${EUREKA_SERVER_PORT:8080}/eureka/
      defaultZone: https://eureka-server.cfapps.eu20.hana.ondemand.com:8080/eureka
  server:
    enable-self-preservation: false
    max-threads-for-peer-replication: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
